import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.nav.home': 'Home',
    'app.nav.triage': 'Advice',
    'app.nav.scan': 'Scan',
    'app.nav.doctors': 'Doctors',
    'app.nav.dashboard': 'Stats',
    'home.hero.badge': 'Live in 13,000 Villages',
    'home.hero.title': 'Your First Line of Care.',
    'home.hero.subtitle': 'ShasthyoAI brings doctor-level guidance to rural Bangladesh through voice-first AI.',
    'home.hero.btn.triage': 'Get Advice',
    'home.hero.btn.scan': 'Scan Meds',
    'home.stats.alert': 'Health Alert',
    'home.stats.dengue': 'Dengue Alert',
    'home.stats.dengue_desc': 'Khulna Division reports rise',
    'home.stats.impact': 'Impact Stats',
    'home.stats.helped': '12k+ Helped',
    'home.stats.helped_desc': 'Community verified reports',
    'home.services.title': 'Core Services',
    'home.services.view_all': 'View All',
    'home.service.triage.title': 'Health Advice',
    'home.service.triage.sub': 'Speak in Bangla, get expert advice',
    'home.service.scan.title': 'Prescription Reader',
    'home.service.scan.sub': 'Understand handwritten meds instantly',
    'home.service.doctors.title': 'Doctor Registry',
    'home.service.doctors.sub': 'Verify BMDC license & rate doctors',
    'home.why.title': 'Why ShasthyoAI?',
    'home.why.voice.title': 'Voice-First:',
    'home.why.voice.desc': 'Designed for those who cannot read or write, supporting regional dialects.',
    'home.why.offline.title': 'Offline-Ready:',
    'home.why.offline.desc': 'Core decision tree works even without internet connectivity.',
    'home.why.accountable.title': 'Accountable:',
    'home.why.accountable.desc': 'We bridge the gap between rural patients and the Health Ministry.',
    'home.why.f1.title': 'Multi-factor AI triage:',
    'home.why.f1.desc': 'Combines your symptoms with profile, district, and weekly disease trend to give a real risk %.',
    'home.why.f2.title': 'Prescription reader:',
    'home.why.f2.desc': 'Scan handwritten prescriptions, see a clean dose grid, and listen aloud in Bangla or English.',
    'home.why.f3.title': 'Verified doctor registry:',
    'home.why.f3.desc': 'BMDC-verified doctors with patient ratings and AI handwriting quality scores.',
    'home.why.f4.title': 'Works offline:',
    'home.why.f4.desc': 'Curated medical knowledge base + on-device AI keep advice flowing without a network.',
    'home.why.f5.title': 'Doctor-audited:',
    'home.why.f5.desc': 'A registered MBBS doctor reviews and signs the AI behaviour every month.',
    'app.nav.profile': 'Profile',
    'more.profile': 'My profile',
    'auth.signin.tab': 'Sign in',
    'auth.signup.tab': 'Sign up',
    'auth.signin.title': 'Welcome back',
    'auth.signin.intro': 'Sign in to see your scanned prescriptions and reviews.',
    'auth.signup.title': 'Create your account',
    'auth.signup.intro': 'Save your prescription history and reviews to your private account on this device.',
    'auth.name': 'Your name',
    'auth.email': 'Email',
    'auth.password': 'Password (min 6 characters)',
    'auth.signin.cta': 'Sign in',
    'auth.signup.cta': 'Create account',
    'auth.privacy': 'Your account stays on this device. Nothing is sent to a server unless you explicitly sync.',
    'profile.signin.title': 'Sign in to see your records',
    'profile.signin.intro': 'Create a free account to store your scanned prescriptions, reviews, and personal medical profile securely on this device.',
    'profile.memberSince': 'Member since',
    'profile.signOut': 'Sign out',
    'profile.rx.title': 'Scanned prescriptions',
    'profile.rx.empty': 'You have not scanned any prescriptions yet. Open the Scan page to add one.',
    'profile.rx.delete': 'Delete',
    'profile.rx.confirmDelete': 'Delete this prescription record? This cannot be undone.',
    'profile.reviews.title': 'My doctor reviews',
    'profile.reviews.empty': 'You have not rated any prescriptions yet.',
    'profile.reviews.prescription': 'prescription clarity',
    'profile.dataNotice': 'Your records are stored in this browser only. Use the same device to see them again.',
    'settings.font.title': 'Text size',
    'settings.font.intro': 'Make all text bigger or smaller. Used across the whole app.',
    'settings.simple.title': 'Make the AI work offline',
    'settings.simple.intro': 'Download the small AI to your phone once. After that it works without internet.',
    'settings.simple.step1': 'Connect to WiFi or fast mobile data (only the first time).',
    'settings.simple.step2': 'Tap the big button below and wait — about 5 minutes on WiFi.',
    'settings.simple.step3': 'Done! From now on, the app works even when your network is down.',
    'settings.simple.cta': 'Download offline AI',
    'settings.simple.hint': '≈300 MB · One-time only · Free after that',
    'settings.simple.downloading.note': 'You can keep using the app. We will notify you when it is ready.',
    'settings.simple.ready': 'Offline AI is ready on this device!',
    'settings.simple.ready.body': 'Triage and Scanner will keep working even without internet. The model stays on this device.',
    'home.tip.title': 'Health Tip of the Day',
    'home.tip.desc': '"Keep yourself hydrated! Drink safe, boiled water to prevent diarrheal diseases this summer."',
    'auth.prompt.title': 'Sign in to continue',
    'auth.prompt.desc': 'To save your history and sync across devices, please sign in.',
    'auth.btn.google': 'Sign in with Google',
    'auth.btn.skip': 'Continue as Guest',
    'scan.title': 'Scan Prescription',
    'scan.subtitle': 'Take a photo of your prescription or lab report',
    'scan.btn.select': 'Select/Take Photo',
    'scan.btn.analyze': 'Analyzing Handwriting...',
    'scan.btn.extract': 'Extract Details',
    'scan.result.doctor_detected': 'Doctor Detected',
    'scan.result.match': 'Match',
    'scan.result.meds_title': 'Medicines & Instructions',
    'scan.btn.save': 'Set Reminder Alarms',
    'triage.disclaimer': 'DISCLAIMER: This is an AI-assisted health advice tool for rural areas. It is NOT a substitute for professional medical advice.',
    'triage.welcome': 'Hello! I am ShasthyoAI. Please tell me your symptoms in Bangla or English.',
    'triage.placeholder': 'Type your symptoms...',
    'triage.thinking': 'ShasthyoAI is thinking...',
    'doctors.search.placeholder': 'Search by name, bmdc, or hospital...',
    'doctors.filter.nearby': 'Nearby',
    'doctors.filter.top': 'Top Rated',
    'doctors.filter.hospital': 'Hospital',
    'doctors.filter.specialist': 'Specialist',
    'doctors.found': 'Doctors Found',
    'doctors.btn.feedback': 'View Feedback',
    'doctors.btn.rate': 'Rate Experience',
    'app.nav.compliance': 'Safety',
    'compliance.title': 'Safety, Compliance & Trust',
    'compliance.intro': 'ShasthyoAI is an AI-assisted advisory tool, not a licensed medical practitioner. Below are the standards we follow and the limits we place on ourselves to protect patients.',
    'compliance.section.limits': 'What our AI will and will not do',
    'compliance.limit.1': 'AI will never prescribe medicines for critical conditions (chest pain, breathing difficulty, unconsciousness, severe bleeding, infant fever, seizure, suicidal thoughts, anaphylaxis, pregnancy emergency).',
    'compliance.limit.2': 'For any critical condition, the AI automatically responds with a referral to a registered MBBS doctor or the nearest hospital.',
    'compliance.limit.3': 'AI guidance is advisory only. All clinical decisions require verification by a licensed doctor.',
    'compliance.limit.4': 'The prescription scanner explains what a doctor has written — it never recommends additional medicines.',
    'compliance.section.standards': 'Standards we follow',
    'compliance.std.bmdc': 'Bangladesh Medical & Dental Council Act 2010 — only licensed practitioners may diagnose and prescribe.',
    'compliance.std.bmdc_code': 'BMDC Code of Professional Conduct & Etiquette — guides doctor verification.',
    'compliance.std.dghs': 'DGHS Telemedicine Practice Guideline 2020 (Bangladesh) — consent, identity verification, record keeping, prescription rules.',
    'compliance.std.dsa': 'Digital Security Act 2018 (Bangladesh) — patient data protection.',
    'compliance.std.who': 'WHO Global Strategy on Digital Health 2020–2025 and Ethics & Governance of AI for Health (2021).',
    'compliance.std.hipaa': 'HIPAA (USA) and GDPR (EU) — adopted as data-handling reference standards.',
    'compliance.section.data': 'How your data is handled',
    'compliance.data.1': 'Symptom text and scanned prescriptions are sent to the AI provider over TLS. We do not sell your data.',
    'compliance.data.2': 'Personally identifying information is minimized. Ministry/surveillance reporting uses district-level aggregates only.',
    'compliance.data.3': 'You can request deletion of your account and all associated records at any time.',
    'compliance.section.emergency': 'Emergency numbers (Bangladesh)',
    'compliance.emergency.999': 'National Emergency (police / fire / ambulance): 999',
    'compliance.emergency.dghs': 'DGHS Health Hotline: 16263',
    'compliance.emergency.suicide': 'Kaan Pete Roi (mental health): 9612119911',
    'compliance.disclaimer.title': 'Important disclaimer',
    'compliance.disclaimer.body': 'ShasthyoAI does not replace medical care. In a medical emergency call 999. If symptoms persist or worsen, see a registered MBBS doctor.',
    'consent.title': 'Before you start',
    'consent.intro': 'ShasthyoAI helps you understand symptoms and prescriptions. To keep you safe, please confirm you understand the following:',
    'consent.item.ai': 'ShasthyoAI is an AI tool, not a doctor. Its advice is informational only.',
    'consent.item.verify': 'For any serious or critical condition, I will see a registered MBBS doctor or go to a hospital.',
    'consent.item.data': 'My symptoms and any uploaded prescriptions will be processed by an AI service to generate advice. Anonymized data may be aggregated to spot disease outbreaks.',
    'consent.item.emergency': 'In a medical emergency I will call 999, not rely on this app.',
    'consent.accept': 'I understand and accept',
    'consent.review': 'Read full safety & privacy notice',
    'safety.referral.banner': 'Referred to a registered MBBS doctor by automated safety rules.',
    'home.nav.dashboard': 'Public Health Dashboard',
    'home.nav.dashboard_sub': 'Live disease reports by district',
    'app.nav.doctor_portal': 'Doctor Portal',
    'app.nav.more': 'More',
    'more.dashboard': 'Public Health Dashboard',
    'more.compliance': 'Safety & Compliance',
    'more.doctor_portal': 'Doctor Portal',
    'more.title': 'More',
    'portal.tag': 'For licensed practitioners',
    'portal.title': 'Doctor Verification Portal',
    'portal.intro': 'Registered MBBS doctors review AI-generated triage answers and prescription summaries before patients act on them.',
    'portal.demo.title': 'Sign in as demo doctor',
    'portal.demo.sub': 'Use the pre-seeded "Dr. Demo Verifier" account (BMDC A-99999) to review pending requests.',
    'portal.demo.cta': 'Continue as demo doctor',
    'portal.onboard.title': 'Apply as a real doctor',
    'portal.onboard.sub': 'Submit BMDC number, qualification, and license. Admin team verifies against the BMDC registry.',
    'portal.onboard.cta': 'Start onboarding',
    'portal.notice': 'BMDC has no public verification API. In production a human admin checks each application against the BMDC registry. In this demo you can self-approve.',
    'portal.form.title': 'Doctor onboarding',
    'portal.form.sub': 'All fields are kept private and used only for credential verification.',
    'portal.form.fullName': 'Full name',
    'portal.form.email': 'Email (optional)',
    'portal.form.bmdc': 'BMDC registration #',
    'portal.form.qualification': 'Qualification',
    'portal.form.specialty': 'Specialty',
    'portal.form.hospital': 'Hospital / clinic',
    'portal.form.district': 'District',
    'portal.form.experience': 'Years of experience',
    'portal.form.license': 'I confirm I have uploaded my BMDC license / qualification certificate.',
    'portal.form.license.sub': 'In production this is a file upload to private storage; in this demo we record the acknowledgement only.',
    'portal.form.submit': 'Submit for admin review',
    'portal.form.error.required': 'Please complete the required fields (name, BMDC #, specialty).',
    'portal.form.error.license': 'License acknowledgement is required before submission.',
    'portal.pending.title': 'Pending admin verification',
    'portal.pending.body': 'Your application is awaiting verification against the BMDC registry. In production you will receive an email when an admin approves your profile.',
    'portal.pending.demoApprove': 'Demo: simulate admin approval',
    'portal.pending.demoNote': 'Only available in this hackathon demo. In production this button does not exist — an admin reviews your credentials manually.',
    'portal.rejected.title': 'Application rejected',
    'portal.signOut': 'Sign out of portal',
    'portal.queue.tag': 'Verified MBBS auditor',
    'portal.kind.triage': 'Triage answer',
    'portal.kind.prescription': 'Prescription scan',
    'portal.flag.critical': 'AI flagged as critical',
    'portal.audit.title': 'Monthly AI audit',
    'portal.audit.intro': 'Review a representative batch of AI outputs the app generates. Rate each for clinical accuracy, then sign the period certification.',
    'portal.audit.progress': 'Samples rated',
    'portal.audit.samples': 'Audit samples',
    'portal.audit.signCta': 'Sign monthly certification',
    'portal.audit.signHint': 'Rate every sample to enable signing.',
    'portal.audit.history': 'Previous certifications',
    'portal.audit.review.title': 'Audit this sample',
    'portal.audit.review.patientInput': 'Patient input',
    'portal.audit.review.aiOutput': 'AI output',
    'portal.audit.review.rateLabel': 'Your assessment',
    'portal.audit.review.notesLabel': 'Notes (optional)',
    'portal.audit.review.notesPlaceholder': 'e.g. Dose threshold should reference paediatric weight bands.',
    'portal.audit.review.save': 'Save rating',
    'portal.audit.review.signedBy': 'Recorded under Dr. {name}, BMDC #{bmdc}',
    'audit.rating.unrated': 'Unrated',
    'audit.rating.accurate': 'Accurate',
    'audit.rating.needs_revision': 'Needs revision',
    'audit.rating.unsafe': 'Unsafe',
    'portal.sign.title': 'Sign monthly certification',
    'portal.sign.body': 'You are signing as the MBBS auditor of record for this period. Your BMDC number and signature time will be stored with the certificate.',
    'portal.sign.notesLabel': 'Summary notes for this period (optional)',
    'portal.sign.notesPlaceholder': 'e.g. Emergency triage flow is appropriate. Suggest stronger paediatric warnings.',
    'portal.sign.confirm': 'Sign certification',
    'portal.sign.disclaimer': 'This certification covers the AI behaviour samples reviewed in this period. It does not authorise individual patient diagnoses, which still require a face-to-face doctor.',
    'compliance.cert.currentTag': 'Current AI behaviour certification',
    'compliance.cert.expiredTag': 'Certification expired — pending re-audit',
    'compliance.cert.signedBy': 'Signed by',
    'compliance.cert.period': 'Audit period',
    'compliance.cert.signedOn': 'Signed',
    'compliance.cert.validUntil': 'valid until',
    'compliance.cert.none.title': 'No active certification',
    'compliance.cert.none.body': 'A registered MBBS doctor has not yet signed off on the current AI behaviour. The Doctor Portal lets a qualified auditor review samples and certify each period.',
    'app.nav.settings': 'Settings',
    'more.settings': 'Settings & offline AI',
    'settings.tag': 'Settings · Offline AI',
    'settings.title': 'Settings',
    'settings.intro': 'Manage on-device AI, connectivity, and privacy. The offline model lets ShasthyoAI keep working when your network drops.',
    'settings.network': 'Network',
    'settings.network.online': 'Online',
    'settings.network.offline': 'Offline',
    'settings.webgpu': 'WebGPU',
    'settings.webgpu.yes': 'Supported',
    'settings.webgpu.no': 'Not supported on this browser',
    'settings.localai.title': 'On-device AI (offline)',
    'settings.localai.intro': 'A small open-source model that runs entirely on your device. Once downloaded, it works without the internet.',
    'settings.localai.download': 'Download offline AI',
    'settings.localai.load': 'Load model into memory',
    'settings.localai.downloading': 'Downloading…',
    'settings.localai.delete': 'Delete offline AI',
    'settings.localai.error': 'Could not load offline AI',
    'settings.localai.disclaim.title': 'One-time download',
    'settings.localai.disclaim.body': 'About ~1.2 GB on first download. Use WiFi if possible. After that the model runs offline with no further data usage.',
    'settings.localai.legacy.title': 'Older offline model still cached',
    'settings.localai.legacy.body': 'You previously downloaded an f16 variant that does not load on this device\'s GPU. Free the space and re-download the new f32 variant above.',
    'settings.localai.legacy.cta': 'Delete old offline model',
    'settings.localai.status.idle': 'Not downloaded',
    'settings.localai.status.loading': 'Downloading',
    'settings.localai.status.cached': 'Cached',
    'settings.localai.status.ready': 'Ready',
    'settings.localai.status.error': 'Error',
    'settings.localai.force.label': 'Always use offline AI',
    'settings.localai.force.sub': 'Default is: use Groq cloud when online (better quality), local model when offline. Tick this to always use the local model.',
    'settings.localai.deleteConfirm.title': 'Delete offline AI?',
    'settings.localai.deleteConfirm.body': 'This frees ~900 MB of storage. You will need to download it again to use ShasthyoAI offline.',
    'settings.manifest.title': 'Model channel',
    'settings.manifest.checking': 'Checking…',
    'settings.manifest.offline': 'Offline — cannot check for updates',
    'settings.manifest.error': 'Could not reach update server',
    'settings.manifest.recommended': 'Recommended',
    'settings.manifest.recheck': 'Recheck',
    'settings.manifest.update_available': 'A newer model revision is available. Delete and re-download to update.',
    'settings.privacy.title': 'Your conversations stay private',
    'settings.privacy.body': 'When the offline model handles your message, nothing leaves your device. Cloud answers go over TLS to Groq and are not stored beyond debug logs.',
    'triage.source.cloud': 'Cloud AI',
    'triage.source.local': 'Offline AI',
    'triage.source.kb': 'Verified medical KB',
    'triage.source.webllm': 'On-device AI (WebGPU)',
    'triage.source.wasm': 'On-device AI (CPU)',
    'triage.source.rules': 'KB best-effort match',
    'triage.engine.localReady': 'On-device AI is loaded as a backup.',
    'triage.engine.localActive': 'Offline mode — using on-device AI.',
    'triage.engine.webllmActive': 'Offline mode — using WebGPU on-device AI.',
    'triage.engine.wasmActive': 'Offline mode — using CPU on-device AI.',
    'triage.engine.rulesActive': 'Offline mode — answering from medical KB. Download an on-device AI in Settings for free-form chat.',
    'triage.profile.label': 'Your profile',
    'triage.profile.edit': 'Edit',
    'profile.title': 'Your profile',
    'profile.intro': 'Helps the AI factor your age, location, and conditions into a personalised risk estimate. Stored only on this device.',
    'profile.age': 'Age',
    'profile.sex': 'Sex',
    'profile.district': 'District',
    'profile.conditions': 'Chronic conditions',
    'profile.pregnancyWeeks': 'Pregnancy weeks',
    'profile.save': 'Save profile',
    'profile.privacy': 'Profile stays in your browser. Never leaves your device unless you sign in.',
    'diag.title': 'AI multi-factor analysis',
    'diag.subtitle': 'Symptoms + profile + regional situation',
    'diag.row.profile': 'Personal profile',
    'diag.row.regional': 'Regional data (IEDCR)',
    'diag.row.who': 'WHO / KB guideline',
    'diag.running': 'Running diagnostic AI…',
    'diag.verdict': 'Risk verdict',
    'diag.reason': 'Reason',
    'diag.warning': 'Warning',
    'diag.nearestHospitals': 'Nearest hospitals',
    'diag.nearestHospital': 'Nearest hospital',
    'diag.noProfile': 'Add your age, district, and conditions for a personalised risk',
    'settings.caps.title': 'This device',
    'settings.caps.intro': 'Detected capabilities and the recommended offline AI tier for this device. Cloud is always preferred when online.',
    'settings.caps.webgpu': 'WebGPU',
    'settings.caps.workgroup': 'GPU workgroup limit',
    'settings.caps.ram': 'Estimated RAM',
    'settings.caps.cores': 'CPU cores',
    'settings.caps.network': 'Network',
    'settings.caps.recommended': 'Recommended offline tier',
    'settings.tf.title': 'On-device AI (universal, CPU)',
    'settings.tf.intro': 'Smaller model that runs without a GPU. Slower (~5–10 sec per reply) but works on any device including low-end Android phones.',
    'settings.tf.download': 'Download & load (≈300 MB)',
    'settings.tf.unload': 'Unload from memory',
    'settings.tf.error': 'Could not load Tier 1 model',
    'settings.tf.status.idle': 'Not loaded',
    'settings.tf.status.loading': 'Downloading / loading',
    'settings.tf.status.ready': 'Ready',
    'settings.tf.status.error': 'Error',
    'settings.tf.disclaim': 'First load downloads ~300 MB to your browser cache. Bangla quality is basic — answers are anchored by the embedded medical knowledge base (RAG) for safety.',
  },
  bn: {
    'app.nav.home': 'হোম',
    'app.nav.triage': 'পরামর্শ',
    'app.nav.scan': 'স্ক্যান',
    'app.nav.doctors': 'ডাক্তার',
    'app.nav.dashboard': 'পরিসংখ্যান',
    'home.hero.badge': '১৩,০০০ গ্রামে সক্রিয়',
    'home.hero.title': 'আপনার চিকিৎসার প্রথম ধাপ।',
    'home.hero.subtitle': 'ভয়েস-ফার্স্ট এআই-এর মাধ্যমে গ্রামীণ বাংলাদেশে ডাক্তারের পরামর্শ পৌঁছে দিচ্ছে ShasthyoAI।',
    'home.hero.btn.triage': 'পরামর্শ নিন',
    'home.hero.btn.scan': 'ওষুধ স্ক্যান',
    'home.stats.alert': 'স্বাস্থ্য সতর্কতা',
    'home.stats.dengue': 'ডেঙ্গু সতর্কতা',
    'home.stats.dengue_desc': 'খুলনা বিভাগে সংক্রমণ বাড়ছে',
    'home.stats.impact': 'প্রভাব পরিসংখ্যান',
    'home.stats.helped': '১২ হাজার+ সাহায্যপ্রাপ্ত',
    'home.stats.helped_desc': 'কমিউনিটি ভেরিফাইড রিপোর্ট',
    'home.services.title': 'আমাদের সেবাসমূহ',
    'home.services.view_all': 'সব দেখুন',
    'home.service.triage.title': 'স্বাস্থ্য পরামর্শ',
    'home.service.triage.sub': 'বাংলায় কথা বলুন, বিশেষজ্ঞ পরামর্শ নিন',
    'home.service.scan.title': 'প্রেসক্রিপশন রিডার',
    'home.service.scan.sub': 'হাতের লেখা ওষুধ মুহূর্তেই বুঝুন',
    'home.service.doctors.title': 'ডাক্তার তালিকা',
    'home.service.doctors.sub': 'BMDC লাইসেন্স যাচাই করুন এবং রেটিং দিন',
    'home.why.title': 'কেন ShasthyoAI?',
    'home.why.voice.title': 'ভয়েস-ফার্স্ট:',
    'home.why.voice.desc': 'যারা পড়তে বা লিখতে পারেন না তাদের জন্য ডিজাইন করা হয়েছে।',
    'home.why.offline.title': 'অফলাইন-রেডি:',
    'home.why.offline.desc': 'ইন্টারনেট ছাড়াই ট্রায়াজ কাজ করে।',
    'home.why.accountable.title': 'জবাবদিহিতা:',
    'home.why.accountable.desc': 'আমরা রোগী এবং স্বাস্থ্য মন্ত্রণালয়ের মধ্যে সেতুবন্ধন তৈরি করি।',
    'home.why.f1.title': 'মাল্টি-ফ্যাক্টর AI ট্রায়াজ:',
    'home.why.f1.desc': 'আপনার উপসর্গ, প্রোফাইল, জেলা ও সাপ্তাহিক রোগ প্রবণতা মিলিয়ে প্রকৃত ঝুঁকি % দেখায়।',
    'home.why.f2.title': 'প্রেসক্রিপশন রিডার:',
    'home.why.f2.desc': 'হাতে লেখা প্রেসক্রিপশন স্ক্যান করুন, পরিষ্কার ডোজ গ্রিড দেখুন, এবং বাংলা বা ইংরেজিতে শুনুন।',
    'home.why.f3.title': 'যাচাইকৃত ডাক্তার তালিকা:',
    'home.why.f3.desc': 'BMDC-যাচাইকৃত ডাক্তার, রোগী রেটিং ও AI হাতের লেখা মান।',
    'home.why.f4.title': 'অফলাইনে কাজ করে:',
    'home.why.f4.desc': 'কিউরেটেড মেডিকেল KB ও অন-ডিভাইস AI নেটওয়ার্ক ছাড়াই পরামর্শ চালু রাখে।',
    'home.why.f5.title': 'ডাক্তার-অডিটেড:',
    'home.why.f5.desc': 'প্রতি মাসে একজন নিবন্ধিত MBBS ডাক্তার AI আচরণ পর্যালোচনা ও স্বাক্ষর করেন।',
    'app.nav.profile': 'প্রোফাইল',
    'more.profile': 'আমার প্রোফাইল',
    'auth.signin.tab': 'সাইন ইন',
    'auth.signup.tab': 'সাইন আপ',
    'auth.signin.title': 'স্বাগতম, আবার',
    'auth.signin.intro': 'আপনার স্ক্যান করা প্রেসক্রিপশন ও রিভিউ দেখতে সাইন ইন করুন।',
    'auth.signup.title': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.signup.intro': 'এই ডিভাইসে আপনার প্রেসক্রিপশন হিস্ট্রি ও রিভিউ ব্যক্তিগতভাবে সংরক্ষণ করুন।',
    'auth.name': 'আপনার নাম',
    'auth.email': 'ইমেইল',
    'auth.password': 'পাসওয়ার্ড (সর্বনিম্ন ৬ অক্ষর)',
    'auth.signin.cta': 'সাইন ইন',
    'auth.signup.cta': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.privacy': 'আপনার অ্যাকাউন্ট শুধু এই ডিভাইসে থাকে। সিঙ্ক না করা পর্যন্ত কিছুই সার্ভারে পাঠানো হয় না।',
    'profile.signin.title': 'নিজের রেকর্ড দেখতে সাইন ইন করুন',
    'profile.signin.intro': 'বিনামূল্যে অ্যাকাউন্ট তৈরি করে নিজের স্ক্যান করা প্রেসক্রিপশন, রিভিউ ও মেডিকেল প্রোফাইল এই ডিভাইসে সুরক্ষিত রাখুন।',
    'profile.memberSince': 'সদস্য:',
    'profile.signOut': 'সাইন আউট',
    'profile.rx.title': 'স্ক্যান করা প্রেসক্রিপশন',
    'profile.rx.empty': 'এখনো কোনো প্রেসক্রিপশন স্ক্যান করেননি। স্ক্যান পেজে গিয়ে যোগ করুন।',
    'profile.rx.delete': 'মুছুন',
    'profile.rx.confirmDelete': 'এই প্রেসক্রিপশন মুছে ফেলবেন? এটি ফেরত আনা যাবে না।',
    'profile.reviews.title': 'আমার ডাক্তার রিভিউ',
    'profile.reviews.empty': 'এখনো কোনো প্রেসক্রিপশন রেট করেননি।',
    'profile.reviews.prescription': 'প্রেসক্রিপশন স্পষ্টতা',
    'profile.dataNotice': 'আপনার রেকর্ড শুধু এই ব্রাউজারে সংরক্ষিত। আবার দেখতে একই ডিভাইস ব্যবহার করুন।',
    'settings.font.title': 'লেখার আকার',
    'settings.font.intro': 'সব লেখা বড় বা ছোট করুন। পুরো অ্যাপে প্রযোজ্য।',
    'settings.simple.title': 'AI কে অফলাইনে চালান',
    'settings.simple.intro': 'একবার ছোট AI ডাউনলোড করুন। এরপর ইন্টারনেট ছাড়াই কাজ করবে।',
    'settings.simple.step1': 'প্রথমবার শুধু — WiFi বা দ্রুত মোবাইল ডেটায় কানেক্ট করুন।',
    'settings.simple.step2': 'নিচের বড় বোতামে টাচ করুন ও অপেক্ষা করুন — WiFi-তে প্রায় ৫ মিনিট।',
    'settings.simple.step3': 'হয়ে গেল! এখন থেকে নেটওয়ার্ক না থাকলেও অ্যাপ কাজ করবে।',
    'settings.simple.cta': 'অফলাইন AI ডাউনলোড করুন',
    'settings.simple.hint': '≈৩০০ MB · একবারই · এরপর বিনামূল্যে',
    'settings.simple.downloading.note': 'অ্যাপ ব্যবহার চালিয়ে যেতে পারেন। প্রস্তুত হলে জানিয়ে দেব।',
    'settings.simple.ready': 'অফলাইন AI এই ডিভাইসে প্রস্তুত!',
    'settings.simple.ready.body': 'এখন থেকে ইন্টারনেট না থাকলেও ট্রায়াজ ও স্ক্যানার কাজ করবে। মডেল এই ডিভাইসেই থাকবে।',
    'home.tip.title': 'আজকের স্বাস্থ্য টিপ',
    'home.tip.desc': '"নিজেকে হাইড্রেটেড রাখুন! এই গরমে ডায়রিয়া প্রতিরোধে নিরাপদ জল পান করুন।।',
    'auth.prompt.title': 'চালিয়ে যেতে সাইন ইন করুন',
    'auth.prompt.desc': 'আপনার হিস্ট্রি সংরক্ষণ করতে এবং সিঙ্ক করতে গুগল দিয়ে লগইন করুন।',
    'auth.btn.google': 'গুগল দিয়ে সাইন ইন',
    'auth.btn.skip': 'অতিথি হিসেবে চালিয়ে যান',
    'scan.title': 'প্রেসক্রিপশন স্ক্যান',
    'scan.subtitle': 'আপনার প্রেসক্রিপশনের ছবি তুলুন বা আপলোড করুন',
    'scan.btn.select': 'ছবি তুলুন/বাছাই করুন',
    'scan.btn.analyze': 'বিশ্লেষণ করা হচ্ছে...',
    'scan.btn.extract': 'তথ্য বের করুন',
    'scan.result.doctor_detected': 'ডাক্তার শনাক্ত করা হয়েছে',
    'scan.result.match': 'ম্যাচ',
    'scan.result.meds_title': 'ওষুধ এবং নির্দেশনা',
    'scan.btn.save': 'ওষুধের রিমাইন্ডার সেট করুন',
    'triage.disclaimer': 'সতর্কবার্তা: এটি একটি এআই স্বাস্থ্য পরামর্শ টুল। এটি পেশাদার চিকিৎসার বিকল্প নয়।',
    'triage.welcome': 'হ্যালো! আমি ShasthyoAI। আপনার সমস্যার কথা বাংলায় বা ইংরেজিতে বলুন।',
    'triage.placeholder': 'আপনার সমস্যা লিখুন...',
    'triage.thinking': 'ShasthyoAI ভাবছে...',
    'doctors.search.placeholder': 'নাম, BMDC বা হাসপাতাল দিয়ে খুঁজুন...',
    'doctors.filter.nearby': 'কাছাকাছি',
    'doctors.filter.top': 'শীর্ষ রেটেড',
    'doctors.filter.hospital': 'হাসপাতাল',
    'doctors.filter.specialist': 'বিশেষজ্ঞ',
    'doctors.found': 'জন ডাক্তার পাওয়া গেছে',
    'doctors.btn.feedback': 'ফিডব্যাক দেখুন',
    'doctors.btn.rate': 'রেটিং দিন',
    'app.nav.compliance': 'সুরক্ষা',
    'compliance.title': 'সুরক্ষা, নীতিমালা ও আস্থা',
    'compliance.intro': 'ShasthyoAI একটি AI সহায়ক টুল, কোনো নিবন্ধিত চিকিৎসক নয়। রোগীর সুরক্ষার জন্য আমরা যেসব নীতি মানি এবং নিজেদের ওপর যে সীমাবদ্ধতা আরোপ করি তা নিচে দেওয়া হলো।',
    'compliance.section.limits': 'আমাদের AI যা করবে এবং যা করবে না',
    'compliance.limit.1': 'গুরুতর অবস্থায় (বুকে ব্যথা, শ্বাসকষ্ট, অজ্ঞান হওয়া, প্রচুর রক্তপাত, শিশুর জ্বর, খিঁচুনি, আত্মহত্যার চিন্তা, এলার্জিক শক, গর্ভাবস্থার জরুরি অবস্থা) AI কখনই ওষুধ সুপারিশ করবে না।',
    'compliance.limit.2': 'যেকোনো গুরুতর অবস্থার জন্য AI স্বয়ংক্রিয়ভাবে নিবন্ধিত MBBS ডাক্তার বা নিকটতম হাসপাতালের পরামর্শ দেবে।',
    'compliance.limit.3': 'AI পরামর্শ শুধুমাত্র তথ্যমূলক। সব চিকিৎসা সিদ্ধান্তে নিবন্ধিত ডাক্তারের যাচাই প্রয়োজন।',
    'compliance.limit.4': 'প্রেসক্রিপশন স্ক্যানার শুধু ডাক্তারের লেখা বুঝিয়ে দেয় — এটি অতিরিক্ত ওষুধ সুপারিশ করে না।',
    'compliance.section.standards': 'আমরা যে মান অনুসরণ করি',
    'compliance.std.bmdc': 'বাংলাদেশ মেডিকেল ও ডেন্টাল কাউন্সিল আইন ২০১০ — শুধু নিবন্ধিত চিকিৎসকই রোগ নির্ণয় ও ওষুধ লিখতে পারেন।',
    'compliance.std.bmdc_code': 'BMDC পেশাগত আচরণ ও সদাচার বিধি — ডাক্তার যাচাইয়ের ভিত্তি।',
    'compliance.std.dghs': 'DGHS টেলিমেডিসিন প্র্যাকটিস গাইডলাইন ২০২০ (বাংলাদেশ) — সম্মতি, পরিচয় যাচাই, নথিভুক্তি, ওষুধ লেখার নিয়ম।',
    'compliance.std.dsa': 'ডিজিটাল নিরাপত্তা আইন ২০১৮ (বাংলাদেশ) — রোগীর তথ্য সুরক্ষা।',
    'compliance.std.who': 'WHO ডিজিটাল স্বাস্থ্য কৌশল ২০২০-২৫ এবং স্বাস্থ্যে AI-এর নৈতিকতা ও পরিচালনা (২০২১)।',
    'compliance.std.hipaa': 'HIPAA (USA) এবং GDPR (EU) — তথ্য পরিচালনার রেফারেন্স স্ট্যান্ডার্ড হিসেবে গৃহীত।',
    'compliance.section.data': 'আপনার তথ্য কীভাবে ব্যবহৃত হয়',
    'compliance.data.1': 'লক্ষণ এবং স্ক্যান করা প্রেসক্রিপশন TLS এনক্রিপশনের মাধ্যমে AI সেবায় পাঠানো হয়। আমরা আপনার তথ্য বিক্রি করি না।',
    'compliance.data.2': 'ব্যক্তিগত শনাক্তকরণযোগ্য তথ্য যথাসম্ভব কম রাখা হয়। মন্ত্রণালয়ের রিপোর্টে শুধুমাত্র জেলা পর্যায়ের অ্যাগ্রিগেট ব্যবহার হয়।',
    'compliance.data.3': 'যেকোনো সময় আপনি অ্যাকাউন্ট ও সংশ্লিষ্ট সব তথ্য মুছে ফেলার অনুরোধ করতে পারেন।',
    'compliance.section.emergency': 'জরুরি নম্বর (বাংলাদেশ)',
    'compliance.emergency.999': 'জাতীয় জরুরি (পুলিশ / ফায়ার / অ্যাম্বুলেন্স): ৯৯৯',
    'compliance.emergency.dghs': 'DGHS স্বাস্থ্য হটলাইন: ১৬২৬৩',
    'compliance.emergency.suicide': 'কান পেতে রই (মানসিক স্বাস্থ্য): ৯৬১২১১৯৯১১',
    'compliance.disclaimer.title': 'গুরুত্বপূর্ণ সতর্কতা',
    'compliance.disclaimer.body': 'ShasthyoAI চিকিৎসার বিকল্প নয়। জরুরি অবস্থায় ৯৯৯-এ কল করুন। লক্ষণ স্থায়ী হলে বা খারাপ হলে নিবন্ধিত MBBS ডাক্তার দেখান।',
    'consent.title': 'শুরু করার আগে',
    'consent.intro': 'ShasthyoAI আপনাকে লক্ষণ ও প্রেসক্রিপশন বুঝতে সাহায্য করে। আপনার সুরক্ষার জন্য নিচের বিষয়গুলো স্বীকার করুন:',
    'consent.item.ai': 'ShasthyoAI একটি AI টুল, ডাক্তার নয়। এর পরামর্শ শুধুমাত্র তথ্যমূলক।',
    'consent.item.verify': 'যেকোনো গুরুতর বা সংকটাপন্ন অবস্থায় আমি নিবন্ধিত MBBS ডাক্তার দেখাব অথবা হাসপাতালে যাব।',
    'consent.item.data': 'পরামর্শ তৈরি করার জন্য আমার লক্ষণ ও আপলোড করা প্রেসক্রিপশন AI সেবায় প্রক্রিয়াজাত হবে। নামহীন ডেটা রোগ পর্যবেক্ষণে ব্যবহার হতে পারে।',
    'consent.item.emergency': 'চিকিৎসা জরুরি অবস্থায় আমি এই অ্যাপের ওপর নির্ভর না করে ৯৯৯-এ কল করব।',
    'consent.accept': 'আমি বুঝেছি এবং সম্মত আছি',
    'consent.review': 'সম্পূর্ণ সুরক্ষা ও গোপনীয়তা নীতিমালা পড়ুন',
    'safety.referral.banner': 'স্বয়ংক্রিয় সুরক্ষা নিয়মের ভিত্তিতে একজন নিবন্ধিত MBBS ডাক্তারের কাছে পাঠানো হয়েছে।',
    'home.nav.dashboard': 'জনস্বাস্থ্য ড্যাশবোর্ড',
    'home.nav.dashboard_sub': 'জেলা অনুযায়ী রোগ রিপোর্ট',
    'app.nav.doctor_portal': 'ডাক্তার পোর্টাল',
    'app.nav.more': 'আরো',
    'more.dashboard': 'জনস্বাস্থ্য ড্যাশবোর্ড',
    'more.compliance': 'সুরক্ষা ও নীতিমালা',
    'more.doctor_portal': 'ডাক্তার পোর্টাল',
    'more.title': 'আরো',
    'portal.tag': 'নিবন্ধিত চিকিৎসকদের জন্য',
    'portal.title': 'ডাক্তার যাচাই পোর্টাল',
    'portal.intro': 'নিবন্ধিত MBBS ডাক্তাররা রোগী AI-উত্পন্ন পরামর্শ ও প্রেসক্রিপশন বিশ্লেষণে কাজ করার আগে পর্যালোচনা করেন।',
    'portal.demo.title': 'ডেমো ডাক্তার হিসেবে সাইন ইন',
    'portal.demo.sub': 'পূর্ব-সিড করা "Dr. Demo Verifier" অ্যাকাউন্ট (BMDC A-99999) ব্যবহার করে অনুরোধ পর্যালোচনা করুন।',
    'portal.demo.cta': 'ডেমো ডাক্তার হিসেবে চালিয়ে যান',
    'portal.onboard.title': 'প্রকৃত ডাক্তার হিসেবে আবেদন',
    'portal.onboard.sub': 'BMDC নম্বর, যোগ্যতা ও লাইসেন্স জমা দিন। অ্যাডমিন BMDC রেজিস্ট্রির বিপরীতে যাচাই করবে।',
    'portal.onboard.cta': 'অনবোর্ডিং শুরু করুন',
    'portal.notice': 'BMDC-এর কোনো পাবলিক যাচাই API নেই। প্রোডাকশনে একজন মানব অ্যাডমিন প্রতিটি আবেদন BMDC রেজিস্ট্রির বিপরীতে পরীক্ষা করেন। এই ডেমোতে আপনি নিজে অনুমোদন করতে পারেন।',
    'portal.form.title': 'ডাক্তার অনবোর্ডিং',
    'portal.form.sub': 'সব তথ্য গোপন রাখা হয় এবং শুধু পরিচয় যাচাইয়ের জন্য ব্যবহৃত হয়।',
    'portal.form.fullName': 'পূর্ণ নাম',
    'portal.form.email': 'ইমেইল (ঐচ্ছিক)',
    'portal.form.bmdc': 'BMDC নিবন্ধন নম্বর',
    'portal.form.qualification': 'যোগ্যতা',
    'portal.form.specialty': 'বিশেষত্ব',
    'portal.form.hospital': 'হাসপাতাল / ক্লিনিক',
    'portal.form.district': 'জেলা',
    'portal.form.experience': 'অভিজ্ঞতার বছর',
    'portal.form.license': 'আমি নিশ্চিত করছি যে আমার BMDC লাইসেন্স / যোগ্যতা সনদ আপলোড করেছি।',
    'portal.form.license.sub': 'প্রোডাকশনে এটি প্রাইভেট স্টোরেজে ফাইল আপলোড; ডেমোতে শুধু স্বীকৃতি রেকর্ড করা হয়।',
    'portal.form.submit': 'অ্যাডমিন পর্যালোচনায় জমা দিন',
    'portal.form.error.required': 'প্রয়োজনীয় ক্ষেত্রগুলি পূরণ করুন (নাম, BMDC #, বিশেষত্ব)।',
    'portal.form.error.license': 'জমা দেওয়ার আগে লাইসেন্স স্বীকৃতি প্রয়োজন।',
    'portal.pending.title': 'অ্যাডমিন যাচাইয়ের অপেক্ষায়',
    'portal.pending.body': 'আপনার আবেদন BMDC রেজিস্ট্রির বিপরীতে যাচাইয়ের জন্য অপেক্ষমাণ। প্রোডাকশনে অ্যাডমিন অনুমোদন করলে আপনি ইমেইল পাবেন।',
    'portal.pending.demoApprove': 'ডেমো: অ্যাডমিন অনুমোদন সিমুলেট করুন',
    'portal.pending.demoNote': 'শুধু এই হ্যাকাথন ডেমোতে উপলব্ধ। প্রোডাকশনে এই বাটন থাকে না — একজন অ্যাডমিন ম্যানুয়ালি যাচাই করেন।',
    'portal.rejected.title': 'আবেদন প্রত্যাখ্যাত',
    'portal.signOut': 'পোর্টাল থেকে সাইন আউট',
    'portal.queue.tag': 'যাচাইকৃত MBBS অডিটর',
    'portal.kind.triage': 'ট্রায়াজ উত্তর',
    'portal.kind.prescription': 'প্রেসক্রিপশন স্ক্যান',
    'portal.flag.critical': 'AI গুরুতর হিসেবে চিহ্নিত করেছে',
    'portal.audit.title': 'মাসিক AI অডিট',
    'portal.audit.intro': 'অ্যাপটি যে ধরনের AI উত্তর তৈরি করে তার একটি প্রতিনিধিত্বমূলক ব্যাচ পর্যালোচনা করুন। প্রতিটির ক্লিনিক্যাল নির্ভুলতা রেট করুন, তারপর সময়কালীন সার্টিফিকেশন স্বাক্ষর করুন।',
    'portal.audit.progress': 'রেটেড নমুনা',
    'portal.audit.samples': 'অডিট নমুনা',
    'portal.audit.signCta': 'মাসিক সার্টিফিকেশন স্বাক্ষর করুন',
    'portal.audit.signHint': 'স্বাক্ষর সক্রিয় করতে প্রতিটি নমুনা রেট করুন।',
    'portal.audit.history': 'পূর্ববর্তী সার্টিফিকেশন',
    'portal.audit.review.title': 'এই নমুনা অডিট করুন',
    'portal.audit.review.patientInput': 'রোগীর ইনপুট',
    'portal.audit.review.aiOutput': 'AI আউটপুট',
    'portal.audit.review.rateLabel': 'আপনার মূল্যায়ন',
    'portal.audit.review.notesLabel': 'নোট (ঐচ্ছিক)',
    'portal.audit.review.notesPlaceholder': 'যেমন: শিশু ডোজ ওজনের উপর ভিত্তি করে উল্লেখ করা উচিত।',
    'portal.audit.review.save': 'রেটিং সংরক্ষণ',
    'portal.audit.review.signedBy': 'রেকর্ড: Dr. {name}, BMDC #{bmdc}',
    'audit.rating.unrated': 'রেট করা হয়নি',
    'audit.rating.accurate': 'নির্ভুল',
    'audit.rating.needs_revision': 'সংশোধন প্রয়োজন',
    'audit.rating.unsafe': 'অনিরাপদ',
    'portal.sign.title': 'মাসিক সার্টিফিকেশন স্বাক্ষর',
    'portal.sign.body': 'এই সময়কালের জন্য আপনি MBBS অডিটর হিসেবে স্বাক্ষর করছেন। আপনার BMDC নম্বর ও স্বাক্ষরের সময় সার্টিফিকেটের সাথে সংরক্ষিত হবে।',
    'portal.sign.notesLabel': 'এই সময়কালের সারসংক্ষেপ নোট (ঐচ্ছিক)',
    'portal.sign.notesPlaceholder': 'যেমন: জরুরি ট্রায়াজ প্রবাহ উপযুক্ত। শিশুদের জন্য আরো জোরালো সতর্কতা প্রয়োজন।',
    'portal.sign.confirm': 'সার্টিফিকেশন স্বাক্ষর',
    'portal.sign.disclaimer': 'এই সার্টিফিকেশন কেবল এই সময়কালে পর্যালোচিত AI আচরণ নমুনাগুলোকে কভার করে। এটি ব্যক্তিগত রোগী নির্ণয়ের অনুমোদন দেয় না — তার জন্য সরাসরি ডাক্তার লাগবে।',
    'compliance.cert.currentTag': 'বর্তমান AI আচরণ সার্টিফিকেশন',
    'compliance.cert.expiredTag': 'সার্টিফিকেশন মেয়াদোত্তীর্ণ — পুনঃঅডিট চলছে',
    'compliance.cert.signedBy': 'স্বাক্ষর করেছেন',
    'compliance.cert.period': 'অডিট সময়কাল',
    'compliance.cert.signedOn': 'স্বাক্ষর',
    'compliance.cert.validUntil': 'বৈধ',
    'compliance.cert.none.title': 'কোনো সক্রিয় সার্টিফিকেশন নেই',
    'compliance.cert.none.body': 'একজন নিবন্ধিত MBBS ডাক্তার এখনো বর্তমান AI আচরণে স্বাক্ষর করেননি। ডাক্তার পোর্টালে একজন যোগ্য অডিটর নমুনা পর্যালোচনা করে প্রতিটি সময়কাল সার্টিফাই করতে পারেন।',
    'app.nav.settings': 'সেটিংস',
    'more.settings': 'সেটিংস ও অফলাইন AI',
    'settings.tag': 'সেটিংস · অফলাইন AI',
    'settings.title': 'সেটিংস',
    'settings.intro': 'অন-ডিভাইস AI, কানেকটিভিটি ও গোপনীয়তা ম্যানেজ করুন। অফলাইন মডেল আপনার নেটওয়ার্ক না থাকলেও ShasthyoAI চালিয়ে রাখে।',
    'settings.network': 'নেটওয়ার্ক',
    'settings.network.online': 'অনলাইন',
    'settings.network.offline': 'অফলাইন',
    'settings.webgpu': 'WebGPU',
    'settings.webgpu.yes': 'সমর্থিত',
    'settings.webgpu.no': 'এই ব্রাউজারে সমর্থিত নয়',
    'settings.localai.title': 'অন-ডিভাইস AI (অফলাইন)',
    'settings.localai.intro': 'একটি ছোট ওপেন-সোর্স মডেল যা সম্পূর্ণভাবে আপনার ডিভাইসে চলে। একবার ডাউনলোড হলে ইন্টারনেট ছাড়া কাজ করে।',
    'settings.localai.download': 'অফলাইন AI ডাউনলোড করুন',
    'settings.localai.load': 'মডেল মেমোরিতে লোড করুন',
    'settings.localai.downloading': 'ডাউনলোড হচ্ছে…',
    'settings.localai.delete': 'অফলাইন AI মুছুন',
    'settings.localai.error': 'অফলাইন AI লোড করা যায়নি',
    'settings.localai.disclaim.title': 'একবার ডাউনলোড',
    'settings.localai.disclaim.body': 'প্রথমবার প্রায় ১.২ GB ডাউনলোড। সম্ভব হলে WiFi ব্যবহার করুন। এরপর মডেল আর কোনো ডেটা ছাড়াই অফলাইনে চলবে।',
    'settings.localai.legacy.title': 'পুরোনো অফলাইন মডেল এখনো ক্যাশে',
    'settings.localai.legacy.body': 'আপনি আগে f16 ভেরিয়েন্ট ডাউনলোড করেছেন যা এই ডিভাইসের GPU-তে লোড হয় না। জায়গা খালি করতে মুছে দিন এবং উপরের নতুন f32 ভেরিয়েন্ট ডাউনলোড করুন।',
    'settings.localai.legacy.cta': 'পুরোনো অফলাইন মডেল মুছুন',
    'settings.localai.status.idle': 'ডাউনলোড করা হয়নি',
    'settings.localai.status.loading': 'ডাউনলোড হচ্ছে',
    'settings.localai.status.cached': 'ক্যাশড',
    'settings.localai.status.ready': 'প্রস্তুত',
    'settings.localai.status.error': 'ত্রুটি',
    'settings.localai.force.label': 'সবসময় অফলাইন AI ব্যবহার করুন',
    'settings.localai.force.sub': 'ডিফল্ট: অনলাইনে Groq ক্লাউড, অফলাইনে লোকাল মডেল। সবসময় লোকাল চাইলে এটি টিক দিন।',
    'settings.localai.deleteConfirm.title': 'অফলাইন AI মুছবেন?',
    'settings.localai.deleteConfirm.body': 'এতে ~৯০০ MB স্টোরেজ মুক্ত হবে। অফলাইন ShasthyoAI ব্যবহারের জন্য আবার ডাউনলোড করতে হবে।',
    'settings.manifest.title': 'মডেল চ্যানেল',
    'settings.manifest.checking': 'যাচাই হচ্ছে…',
    'settings.manifest.offline': 'অফলাইন — আপডেট চেক করা যাচ্ছে না',
    'settings.manifest.error': 'আপডেট সার্ভারে পৌঁছানো যায়নি',
    'settings.manifest.recommended': 'সুপারিশকৃত',
    'settings.manifest.recheck': 'পুনঃ যাচাই',
    'settings.manifest.update_available': 'একটি নতুন মডেল রিভিশন উপলব্ধ। আপডেট করতে মুছে আবার ডাউনলোড করুন।',
    'settings.privacy.title': 'আপনার কথোপকথন গোপন থাকে',
    'settings.privacy.body': 'অফলাইন মডেল ব্যবহারের সময় কিছুই আপনার ডিভাইস ছাড়ে না। ক্লাউড উত্তর TLS-এর মাধ্যমে Groq-এ যায় এবং ডিবাগ লগ ছাড়া সংরক্ষণ করা হয় না।',
    'triage.source.cloud': 'ক্লাউড AI',
    'triage.source.local': 'অফলাইন AI',
    'triage.source.kb': 'যাচাইকৃত মেডিকেল KB',
    'triage.source.webllm': 'অন-ডিভাইস AI (WebGPU)',
    'triage.source.wasm': 'অন-ডিভাইস AI (CPU)',
    'triage.source.rules': 'KB সর্বোত্তম মিল',
    'triage.engine.localReady': 'অন-ডিভাইস AI ব্যাকআপ হিসেবে প্রস্তুত।',
    'triage.engine.localActive': 'অফলাইন মোড — অন-ডিভাইস AI ব্যবহার হচ্ছে।',
    'triage.engine.webllmActive': 'অফলাইন মোড — WebGPU অন-ডিভাইস AI।',
    'triage.engine.wasmActive': 'অফলাইন মোড — CPU অন-ডিভাইস AI।',
    'triage.engine.rulesActive': 'অফলাইন মোড — মেডিকেল KB থেকে উত্তর। ফ্রি-ফর্ম চ্যাটের জন্য সেটিংসে অন-ডিভাইস AI ডাউনলোড করুন।',
    'triage.profile.label': 'আপনার প্রোফাইল',
    'triage.profile.edit': 'সম্পাদনা',
    'profile.title': 'আপনার প্রোফাইল',
    'profile.intro': 'বয়স, অবস্থান ও রোগের ইতিহাস মাথায় রেখে ঝুঁকির ব্যক্তিগত অনুমান তৈরিতে সহায়তা করে। শুধু এই ডিভাইসে সংরক্ষিত।',
    'profile.age': 'বয়স',
    'profile.sex': 'লিঙ্গ',
    'profile.district': 'জেলা',
    'profile.conditions': 'দীর্ঘস্থায়ী রোগ',
    'profile.pregnancyWeeks': 'গর্ভাবস্থার সপ্তাহ',
    'profile.save': 'প্রোফাইল সংরক্ষণ',
    'profile.privacy': 'প্রোফাইল আপনার ব্রাউজারেই থাকে। সাইন ইন না করলে ডিভাইস ছাড়ে না।',
    'diag.title': 'এআই মাল্টি-ফ্যাক্টর বিশ্লেষণ',
    'diag.subtitle': 'উপসর্গ + প্রোফাইল + আঞ্চলিক পরিস্থিতি',
    'diag.row.profile': 'ব্যক্তিগত প্রোফাইল',
    'diag.row.regional': 'আঞ্চলিক ডেটা (IEDCR)',
    'diag.row.who': 'WHO / KB নির্দেশিকা',
    'diag.running': 'এআই ডায়াগনস্টিক চলছে…',
    'diag.verdict': 'ঝুঁকি রায়',
    'diag.reason': 'কারণ',
    'diag.warning': 'সতর্কতা',
    'diag.nearestHospitals': 'নিকটস্থ হাসপাতাল',
    'diag.nearestHospital': 'নিকটস্থ হাসপাতাল',
    'diag.noProfile': 'ব্যক্তিগত ঝুঁকির জন্য বয়স, জেলা ও রোগের তথ্য যোগ করুন',
    'settings.caps.title': 'এই ডিভাইস',
    'settings.caps.intro': 'এই ডিভাইসের জন্য সনাক্তকৃত ক্ষমতা ও সুপারিশকৃত অফলাইন AI স্তর। অনলাইনে সবসময় ক্লাউড অগ্রাধিকার।',
    'settings.caps.webgpu': 'WebGPU',
    'settings.caps.workgroup': 'GPU ওয়ার্কগ্রুপ সীমা',
    'settings.caps.ram': 'আনুমানিক RAM',
    'settings.caps.cores': 'CPU কোর',
    'settings.caps.network': 'নেটওয়ার্ক',
    'settings.caps.recommended': 'সুপারিশকৃত অফলাইন স্তর',
    'settings.tf.title': 'অন-ডিভাইস AI (সর্বজনীন, CPU)',
    'settings.tf.intro': 'GPU ছাড়াই চলে এমন ছোট মডেল। ধীর (~৫-১০ সেকেন্ড প্রতি উত্তর) কিন্তু লো-এন্ড অ্যান্ড্রয়েডসহ যেকোনো ডিভাইসে কাজ করে।',
    'settings.tf.download': 'ডাউনলোড ও লোড (≈৩০০ MB)',
    'settings.tf.unload': 'মেমোরি থেকে আনলোড',
    'settings.tf.error': 'Tier 1 মডেল লোড করা যায়নি',
    'settings.tf.status.idle': 'লোড করা হয়নি',
    'settings.tf.status.loading': 'ডাউনলোড / লোড হচ্ছে',
    'settings.tf.status.ready': 'প্রস্তুত',
    'settings.tf.status.error': 'ত্রুটি',
    'settings.tf.disclaim': 'প্রথম লোডে ব্রাউজার ক্যাশে ~৩০০ MB ডাউনলোড। বাংলা মান প্রাথমিক — সুরক্ষার জন্য উত্তরগুলো এমবেডেড মেডিকেল KB (RAG) দ্বারা অ্যাঙ্কর করা।',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('bn');

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
